import { Html, Head, Main, NextScript } from 'next/document';



export default function Document() {

  return (
    <Html
      lang="en"
      className='w-full scroll-smooth'
    >
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>
      <title>Budget-api</title>
      <body className='w-full'>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}